"""Build step.

1. assets/models.json  ->  src/ReplicatedStorage/TenShadows/ModelData.luau
2. src/**              ->  TenShadows.rbxlx  (open this file directly in Roblox Studio)

The src/ tree uses Rojo naming, so `rojo serve` works too:
  folder -> Folder, *.server.luau -> Script, *.client.luau -> LocalScript, *.luau -> ModuleScript

Run:  python3 tools/models.py && python3 tools/build.py
"""
import json
import os
from xml.sax.saxutils import escape

ROOT = os.path.normpath(os.path.join(os.path.dirname(os.path.abspath(__file__)), ".."))
SRC = os.path.join(ROOT, "src")
MODELS_JSON = os.path.join(ROOT, "assets", "models.json")
MODELDATA = os.path.join(SRC, "ReplicatedStorage", "TenShadows", "ModelData.luau")
PLACE = os.path.join(ROOT, "TenShadows.rbxlx")


def lua_num(v):
    v = round(float(v), 3)
    return str(int(v)) if v == int(v) else repr(v)


def lua_vec(v):
    return "{" + ", ".join(lua_num(x) for x in v) + "}"


def part_top(p):
    sx, sy, sz = p["size"]
    if p["shape"] == "Ball":
        return p["pos"][1] + min(p["size"]) / 2
    return p["pos"][1] + max(sx, sy, sz) / 2 if p["shape"] == "Cylinder" else p["pos"][1] + sy / 2


def write_modeldata():
    with open(MODELS_JSON) as f:
        models = json.load(f)
    out = [
        "-- AUTO-GENERATED by tools/build.py from assets/models.json. Do not edit by hand;",
        "-- change tools/models.py and rebuild instead.",
        "-- Part = {Name, Shape, Size, Pos, RotDegrees, RGB, Material, Group, Transparency}",
        "return {",
    ]
    for name, m in models.items():
        height = max(part_top(p) for p in m["parts"])
        out.append(f"\t{name} = {{")
        out.append(f"\t\tHeight = {lua_num(height)},")
        if "root" in m:
            out.append(f"\t\tHipHeight = {lua_num(m['hipHeight'])},")
            out.append(f"\t\tRoot = {{ Size = {lua_vec(m['root']['size'])}, Pos = {lua_vec(m['root']['pos'])} }},")
        out.append("\t\tJoints = {")
        for jn, j in m["joints"].items():
            out.append(f"\t\t\t{jn} = {{ Part0 = \"{j['part0']}\", Pivot = {lua_vec(j['pivot'])} }},")
        out.append("\t\t},")
        out.append("\t\tParts = {")
        for p in m["parts"]:
            out.append(
                "\t\t\t{" + ", ".join([
                    f"\"{p['name']}\"", f"\"{p['shape']}\"", lua_vec(p["size"]), lua_vec(p["pos"]),
                    lua_vec(p["rot"]), lua_vec(p["color"]), f"\"{p['material']}\"", f"\"{p['group']}\"",
                    lua_num(p["transparency"]),
                ]) + "},"
            )
        out.append("\t\t},")
        out.append("\t},")
    out.append("}")
    with open(MODELDATA, "w") as f:
        f.write("\n".join(out) + "\n")
    print(f"wrote {os.path.relpath(MODELDATA, ROOT)} ({len(models)} models)")


# ---------------------------------------------------------------- rbxlx
_ref = [0]


def ref():
    _ref[0] += 1
    return f"RBX{_ref[0]:08X}"


def cdata(text):
    return "<![CDATA[" + text.replace("]]>", "]]]]><![CDATA[>") + "]]>"


def item(cls, name, children="", extra=""):
    return (f'<Item class="{cls}" referent="{ref()}"><Properties>'
            f'<string name="Name">{escape(name)}</string>{extra}</Properties>{children}</Item>')


def script_item(path):
    base = os.path.basename(path)
    with open(path, encoding="utf-8") as f:
        source = f.read()
    if base.endswith(".server.luau"):
        cls, name = "Script", base[: -len(".server.luau")]
    elif base.endswith(".client.luau"):
        cls, name = "LocalScript", base[: -len(".client.luau")]
    else:
        cls, name = "ModuleScript", base[: -len(".luau")]
    return item(cls, name, extra=f'<ProtectedString name="Source">{cdata(source)}</ProtectedString>')


def tree(path):
    kids = []
    for entry in sorted(os.listdir(path)):
        full = os.path.join(path, entry)
        if os.path.isdir(full):
            kids.append(item("Folder", entry, tree(full)))
        elif entry.endswith(".luau"):
            kids.append(script_item(full))
    return "".join(kids)


def sourcemap_node(path, name, cls):
    node = {"name": name, "className": cls, "children": []}
    for entry in sorted(os.listdir(path)):
        full = os.path.join(path, entry)
        rel = os.path.relpath(full, ROOT)
        if os.path.isdir(full):
            node["children"].append(sourcemap_node(full, entry, "Folder"))
        elif entry.endswith(".server.luau"):
            node["children"].append({"name": entry[:-12], "className": "Script", "filePaths": [rel]})
        elif entry.endswith(".client.luau"):
            node["children"].append({"name": entry[:-12], "className": "LocalScript", "filePaths": [rel]})
        elif entry.endswith(".luau"):
            node["children"].append({"name": entry[:-5], "className": "ModuleScript", "filePaths": [rel]})
    return node


def write_sourcemap():
    """Same shape as `rojo sourcemap`, so luau-lsp can resolve require(script.Parent.X)."""
    sp = sourcemap_node(os.path.join(SRC, "StarterPlayer", "StarterPlayerScripts"), "StarterPlayerScripts", "StarterPlayerScripts")
    tree_ = {"name": "TenShadows", "className": "DataModel", "children": [
        sourcemap_node(os.path.join(SRC, "ReplicatedStorage"), "ReplicatedStorage", "ReplicatedStorage"),
        sourcemap_node(os.path.join(SRC, "ServerScriptService"), "ServerScriptService", "ServerScriptService"),
        {"name": "StarterPlayer", "className": "StarterPlayer", "children": [sp]},
    ]}
    with open(os.path.join(ROOT, "sourcemap.json"), "w") as f:
        json.dump(tree_, f, indent=1)
    print("wrote sourcemap.json")


def write_place():
    services = [
        item("ReplicatedStorage", "ReplicatedStorage", tree(os.path.join(SRC, "ReplicatedStorage"))),
        item("ServerScriptService", "ServerScriptService", tree(os.path.join(SRC, "ServerScriptService"))),
        item("StarterPlayer", "StarterPlayer",
             item("StarterPlayerScripts", "StarterPlayerScripts",
                  tree(os.path.join(SRC, "StarterPlayer", "StarterPlayerScripts")))),
    ]
    xml = ('<roblox xmlns:xmime="http://www.w3.org/2005/05/xmlmime" '
           'xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" '
           'xsi:noNamespaceSchemaLocation="http://www.roblox.com/roblox.xsd" version="4">'
           '<External>null</External><External>nil</External>'
           + "".join(services) + "</roblox>\n")
    with open(PLACE, "w", encoding="utf-8") as f:
        f.write(xml)
    print(f"wrote {os.path.relpath(PLACE, ROOT)} ({len(xml) // 1024} KB)")


if __name__ == "__main__":
    write_modeldata()
    write_place()
    write_sourcemap()
